[package]
name = "stm32tesseract-gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.0"
portable-pty = "0.8.1"
strip-ansi-escapes = "0.2.0"
once_cell = "1.18.0"
native-dialog = { version = "0.6.4", features = [
    "windows_dpi_awareness",
    "windows_visual_styles",
] }

[build-dependencies]
slint-build = "1.0"
