name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
        - os: windows-latest
        - os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    # Workaround for https://github.com/rust-skia/rust-skia/issues/1049
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
